package app.fynlo.ui

internal fun ledgerNavigationTitle(route: String?): String = when (route?.substringBefore('?')) {
    null, "home" -> "Fynlo Ledger"
    "loans_hub", "lending" -> "Loans"
    "debts" -> "Debts"
    "invest" -> "Investments"
    "spend" -> "Expenses"
    "reports_hub" -> "Reports"
    "history" -> "History"
    "settings" -> "Settings"
    "book_check" -> "Book check"
    "about" -> "About"
    "people" -> "Contact book"
    "budgets" -> "Budgeting"
    "goals" -> "Savings goals"
    "profile" -> "Profile & security"
    "flow_wizard" -> "Money movement"
    "projects" -> "Projects"
    "recurring" -> "Recurring transactions"
    "monthly" -> "Monthly summary"
    "profit_loss" -> "Profit & loss"
    "debt_payoff" -> "Debt payoff"
    "net_worth_hist" -> "Net worth history"
    "money_flow" -> "Money flow"
    "loan_calc" -> "EMI calculator"
    "collection_calendar" -> "Collection calendar"
    "interest_income" -> "Interest income"
    "global_search" -> "Search"
    else -> "Ledger"
}
